
/*Create a class Account having private instance member Id, Name Balanceamt. 
 * Id should be generated by application. 
 * Create method deposit who’s job is to increase Balanceamtby the amout deposited by account holder.
 * Create method withdraw who’s job is to decrease Balanceamt by the amount  withdrawn by account holder. 
 * Write method display which will display name and Balanceamt. 
 * Your application should generate only 3 object, if you try to generate 4 th object it should display message can not create object. 
 * This application will be classlibrary.
Create console application and use this class library. Create at least two object of account class and deposit and withdraw money.
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ClassLAmt
{
    public class Account
    {
        static int id;
        string name;
        double BalanceAmt;

        static Account()
        {
            Console.WriteLine("State bank of India");
        }

        public Account(string name, double BalanceAmt)
        {
            this.name = name;
            this.BalanceAmt = BalanceAmt;
            id=++id;
        }
        public void deposite(int amt)
        {
            BalanceAmt += amt;
        }
        public void withdraw(int amt)
        {
            BalanceAmt -= amt;
        }
        public void disp()
        {
            Console.WriteLine("{0}  {1} ", name, BalanceAmt);
        }

        public void checkID()
        {
            if (id > 3)
            {
                throw new Exception("Only Three Objects are allowed");
            }
        }
    }


}
