

/*
 * Q2. Create a class school, having array of student object. 
 * Create a class student having member variable rollnumber, name, marks . 
 * rollnumber should be generated by application. When you load application display school name. 
 * Display all student name and marks.
 */

using System;

namespace School
{

    public class student
    {
        int rollno;
       
        string name;
        int marks;

        static int AutoRollno;

        public student(string name, int mks)
        {
            rollno = ++AutoRollno;
            Name = name;
            Marks = mks;
        }
        public int ROLLNO
        {
            get { return rollno; }

        }

        public string Name
        {
            get { return name; }

            set { name = value; }
        }
        public int  Marks
        {
            get { return marks; }

            set { marks = value; }
        }

        public override string ToString()
        {
            return string.Format("Id= {0}  Name= {1}  Marks= {2}", ROLLNO, Name, Marks);
        }

    }

    public class school
    {
        student[] arr = new student[3];
        
        static school()
        {
        Console.WriteLine("SMVITA");
        }

        public school()
        {
            arr[0] = new student("akash", 100);
            arr[1] = new student("vaibhav", 50);
            arr[2] = new student("anand", 25);
        }

        public void disp()
        {
            for (int i = 0; i < arr.Length; i++)
            {
               // Console.WriteLine(arr[i]);
                Console.WriteLine("Id= {0}  Name= {1}  Marks= {2}", arr[i].ROLLNO, arr[i].Name, arr[i].Marks);
            }   
        }

    }


    class Progrm
    {
        static void Main(string[] args)
        {
            school ob = new school();
            ob.disp();
            Console.ReadLine();
        }
    }
}
