
///*
// * Create a class Employee having private instance member 
//id- id is readonly property and generated by your application
//name- write getter setter
//salary- write getter setter
//net salary
//Write method who’s job is to deduct TDS 10% and return tax amount and set netsalary instance member after deducting tax.
//Declare TDS as static variable.
//Your application should create only 3 object if you try to create 4th object it should throw exception.
//Give appropriate validation like salary can not be 0 or negative, maximum
//Salary allowed is 50000 if you try to set more then 50000 it should give some error message.
//When you run your application it should print name of company.

// * */
//using System;

//namespace Emp1
//{
//    public class Employee
//    {
//        int id;
//        string name;
//        double salary;
//        double netsalary;

//        static readonly double TDS;
//        static int getId;
//        const int maxcap=2;
//        const int maxsal=50000;

//        static Employee()
//        {
//          TDS=0.1;
//          Console.WriteLine("welcome to Tia");
//        }

//        public Employee(string name,double salary)
//        {
//            if(maxcap>getId)
//            {
//                if(maxsal>=salary && salary>0 )
//                {
//                    Name = name;
//                    Salary = salary;
//                }
//                else
//                {
//                    throw new Exception("check entered salary");
//                }

//            }
//            else
//            {
//               throw new Exception("capacity is full");
//            }
            
//        }


//        public string Name
//        {
//            set
//            {
//                name = value;
//            }
//            get
//            {
//                return name;
//            }
//        }

//        public double Salary
//        {
//            set
//            {
//                salary = value;
//            }
//            get
//            {
//                return salary;
//            }
//        }

//        public double CalNetSalary()
//        {
//            netsalary = salary - salary * TDS;
//            return netsalary;
//        }

//        public void disp()
//        {
//            Console.WriteLine("Name= {0} NetSal= {1}", name, CalNetSalary());
//        }

//    }
//}
